### ISSUE TITLE
Getting search related issue

### ISSUE THREAD

**Issue by RYG81** [ask0ldd/OsspitaUI#4]
Hey,
After fixing that ollama thing I managed to run it and first thing I tried is do search and bam i got this error

searchQuery : `inference calls` `build.nvidia.com`                                                                      https://links.duckduckgo.com/d.js?q=%60inference+calls%60+%60build.nvidia.com%60&l=en-us&p=1&kl=wt-wt&s=0&dl=en&ct=US&df=a&vqd=4-233184328542209728539902244176624827220&sp=1&bpa=1&biaexp=b&msvrtexp=b&videxp=a&nadse=b&eclsexp=a&stiaexp=a&tjsexp=b&related=b&msnexp=a                                                                                                TypeError: Cannot read properties of null (reading '1')                                                                     at Object.search (E:\0000AITools\OsspitaUI-a1.0.4-2\Back\services\duckduckfix.service.js:74:70)                         at process.processTicksAndRejections (node:internal/process/task_queues:105:5)                                          at async E:\0000AITools\OsspitaUI-a1.0.4-2\Back\controllers\scraping.controller.js:14:30

**Comment by ask0ldd** [comment]
Unfortunately, the Duck-Duck-Scrape library used by OSspita for web searches has been quite unstable lately. It has been so frustrating that I have implemented my own solution, which will be included in the next version coming very soon.

**Comment by RYG81** [comment]
![image](https://github.com/user-attachments/assets/dd20d6cd-d8f4-49f3-a529-a8088b4089a5)
uploaded document process? NO idea whats going on.

**Comment by ask0ldd** [comment]
First of all, I want to thank you for your help. Your feedback is truly valuable, especially when users like you take the time to share their experiences. Unfortunately, there were some issues with the library I used to parse the PDF files; it couldn't open certain documents. I have already made some changes for the new version of the application, but I will also try to download the PDF you were using to see if it resolves your specific case. Once again, thank you very much for your help.

**Comment by ask0ldd** [comment]
I couldn't access that specific file, but when I tried some other files from the NVIDIA website, I had no trouble at all. Therefore, I guess the new version of OSspita will fix this bug :D

**Comment by RYG81** [comment]
I got some ideas if you like
1. Support for audio and video models or option to connect to other software like comfyui
2. ad a node based creator tool (something similar to your chain thing but more advance
3. Support for cogvlm model which is I think best vision model out there

These just basic ideas i have, may be in future i add more.

**Comment by ask0ldd** [comment]
Those are all great ideas!

1- Someone asked me 2 days ago to include a way to hook ComfyUI to OSspita, and now it is topping my priority list.

2- I had the same idea when I launched the agent chaining feature! It is a lot of work since it will require a dedicated interface and some very complex logic, but this tool could really be a gamechanger if RAG and websearch have their own nodes.

3- Unfortunately, right now CogVLM is not supported by Ollama or LlamaCpp. But since Ollama is little by little forging its own path, there is hope.

Thanks a lot for your contribution! Be sure that ideas 1 & 2 will soon come to life!

P.S.: The Alpha 1.0.5 version is now online. I hope it will handle your PDF file without any issues.
